#!/bin/bash

# Valéry Ozenne, Julie Magat, September 2020

FOLDER=/home/valery/Reseau/Dicom/BRUKER/JulieHR/METHODO_article/manip_2019/Figures_Github/Gifs/

GIFS[0]=timelaps_heart1_SAG_400.gif
GIFS[1]=timelaps_heart2_SAG_300.gif
GIFS[2]=timelaps_heart3_SAG_400.gif




for SAMPLE in "${!GIFS[@]}"; 
do
cp ${FOLDER}/${GIFS[$SAMPLE]} Gifs/.

done
